# Generated by Django 5.2.14 on 2026-07-15 07:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_officeschedule'),
        ('employees', '0006_employeeleaverule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('consultant', models.CharField(blank=True, max_length=255)),
                ('main_contractor', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('hvac_capacity_tr', models.DecimalField(blank=True, decimal_places=2, help_text='Capacity in Tons of Refrigeration', max_digits=10, null=True)),
                ('system_type', models.CharField(choices=[('VRF', 'VRF'), ('Chiller', 'Chiller'), ('Split', 'Split'), ('Package Unit', 'Package Unit')], max_length=50)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Delayed', 'Delayed'), ('Completed', 'Completed')], default='Not Started', max_length=50)),
                ('progress_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='employees.employeeprofile')),
                ('site_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_engineer_projects', to='employees.employeeprofile')),
            ],
        ),
    ]
