# Generated by Django 5.2.14 on 2026-07-15 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_dailyprogresslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trade', models.CharField(choices=[('Project Engineer', 'Project Engineer'), ('Site Engineer', 'Site Engineer'), ('Supervisor', 'Supervisor'), ('Duct Technician', 'Duct Technician'), ('Pipe Fitter', 'Pipe Fitter'), ('Electrician', 'Electrician'), ('Insulation Team', 'Insulation Team'), ('Helper', 'Helper')], max_length=50)),
                ('required_count', models.PositiveIntegerField()),
                ('present_count', models.PositiveIntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpower_logs', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'date', 'trade')},
            },
        ),
    ]
