# Generated by Django 5.2.14 on 2026-07-15 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_manpowerdeployment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('required_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='projects.project')),
            ],
        ),
    ]
