# Generated by Django 5.2.14 on 2026-07-15 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSignOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_manager_name', models.CharField(blank=True, max_length=255)),
                ('project_manager_signed_at', models.DateTimeField(blank=True, null=True)),
                ('site_engineer_name', models.CharField(blank=True, max_length=255)),
                ('site_engineer_signed_at', models.DateTimeField(blank=True, null=True)),
                ('consultant_name', models.CharField(blank=True, max_length=255)),
                ('consultant_signed_at', models.DateTimeField(blank=True, null=True)),
                ('client_representative_name', models.CharField(blank=True, max_length=255)),
                ('client_representative_signed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sign_off', to='projects.project')),
            ],
        ),
    ]
