# Generated by Django 5.2.14 on 2026-07-15 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_projectsignoff"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="project",
            name="system_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VRF", "VRF"),
                    ("Chiller", "Chiller"),
                    ("Split", "Split"),
                    ("Package Unit", "Package Unit"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="projects.projecttype",
            ),
        ),
    ]
