# Generated by Django 5.2.14 on 2026-07-15 18:46

from django.db import migrations


def seed_project_type(apps, schema_editor):
    ProjectType = apps.get_model('projects', 'ProjectType')
    Project = apps.get_model('projects', 'Project')
    hvac_type, _ = ProjectType.objects.get_or_create(name='HVAC Installation')
    Project.objects.all().update(project_type=hvac_type)

def reverse_seed_project_type(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_projecttype_alter_project_system_type_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_project_type, reverse_seed_project_type),
    ]
