# Generated by Django 5.2.14 on 2026-07-15 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_project_project_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="projects.projecttype",
            ),
        ),
    ]
