# Generated by Django 5.2.14 on 2026-07-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_alter_project_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="client_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="consultant_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
