# Generated by Django 5.2.14 on 2026-07-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_client_email_project_consultant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='employee_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='points',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
