# Generated by Django 5.2.14 on 2026-07-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projecttask_completed_at_projecttask_employee_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttask',
            options={'ordering': ['order'], 'permissions': [('assign_projecttask', 'Can assign project task')]},
        ),
    ]
