# Generated by Django 5.2.14 on 2026-07-18 05:37

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_projecttask_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='assignment_attachment',
            field=models.FileField(blank=True, null=True, upload_to='projects/task_attachments/%Y/%m/', validators=[apps.projects.models.validate_task_attachment]),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='completion_attachment',
            field=models.FileField(blank=True, null=True, upload_to='projects/task_attachments/%Y/%m/', validators=[apps.projects.models.validate_task_attachment]),
        ),
    ]
