# Generated by Django 5.2.14 on 2026-07-18 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projecttask_assignment_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project'),
        ),
    ]
