# Generated by Django 5.2.14 on 2026-07-18 16:05

from django.db import migrations, models


def copy_personnel_data(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for project in Project.objects.all():
        if project.project_manager_id:
            project.project_managers.add(project.project_manager_id)
        if project.site_engineer_id:
            project.site_engineers.add(project.site_engineer_id)


def reverse_personnel_data(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for project in Project.objects.all():
        first_pm = project.project_managers.first()
        if first_pm:
            project.project_manager = first_pm
        first_se = project.site_engineers.first()
        if first_se:
            project.site_engineer = first_se
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0011_employeeprofile_is_project_manager"),
        ("projects", "0016_make_projecttask_project_nullable"),
    ]

    operations = [
        # 1. Add new ManyToMany fields
        migrations.AddField(
            model_name="project",
            name="project_managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="managed_projects",
                to="employees.employeeprofile",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="member_projects",
                to="employees.employeeprofile",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="site_engineers",
            field=models.ManyToManyField(
                blank=True,
                related_name="site_engineer_projects",
                to="employees.employeeprofile",
            ),
        ),
        # 2. Copy the data
        migrations.RunPython(copy_personnel_data, reverse_code=reverse_personnel_data),
        # 3. Remove old ForeignKey fields
        migrations.RemoveField(
            model_name="project",
            name="project_manager",
        ),
        migrations.RemoveField(
            model_name="project",
            name="site_engineer",
        ),
    ]
