# Generated by Django 5.2.14 on 2026-07-18 18:52

import apps.projects.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_remove_project_project_manager_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="projects/task_attachments/%Y/%m/",
                        validators=[apps.projects.models.validate_task_attachment],
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("assignment", "Assignment / Reference"),
                            ("completion", "Completion / Proof"),
                        ],
                        default="assignment",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="projects.projecttask",
                    ),
                ),
            ],
        ),
    ]
