# Generated by Django 5.2.14 on 2026-07-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_projecttaskreply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttask",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Started", "Not Started"),
                    ("In Progress", "In Progress"),
                    ("Delayed", "Delayed"),
                    ("Under Review", "Under Review"),
                    ("Completed", "Completed"),
                ],
                default="Not Started",
                max_length=50,
            ),
        ),
    ]
