# Generated by Django 5.2.14 on 2026-07-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_projecttask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='pending_employee_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='pending_progress_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
    ]
