# Generated by Django 5.2.14 on 2026-07-19 07:57

import uuid
from django.db import migrations, models

def gen_uuids_progress(apps, schema_editor):
    MyModel = apps.get_model('projects', 'DailyProgressLog')
    for row in MyModel.objects.filter(sync_uuid__isnull=True):
        row.sync_uuid = uuid.uuid4()
        row.save(update_fields=['sync_uuid'])

def gen_uuids_manpower(apps, schema_editor):
    MyModel = apps.get_model('projects', 'ManpowerDeployment')
    for row in MyModel.objects.filter(sync_uuid__isnull=True):
        row.sync_uuid = uuid.uuid4()
        row.save(update_fields=['sync_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_projecttask_pending_employee_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogresslog',
            name='client_event_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyprogresslog',
            name='sync_uuid',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuids_progress, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='dailyprogresslog',
            name='sync_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='dailyprogresslog',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manpowerdeployment',
            name='client_event_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manpowerdeployment',
            name='sync_uuid',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuids_manpower, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='manpowerdeployment',
            name='sync_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='manpowerdeployment',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
