# Generated by Django 6.0.7 on 2026-08-13 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_dailyprogresslog_client_event_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttask",
            name="actual_finish",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="actual_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="baseline_finish",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="baseline_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="is_milestone",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dep_type",
                    models.CharField(
                        choices=[
                            ("FS", "Finish-to-Start"),
                            ("SS", "Start-to-Start"),
                            ("FF", "Finish-to-Finish"),
                            ("SF", "Start-to-Finish"),
                        ],
                        default="FS",
                        max_length=2,
                    ),
                ),
                (
                    "lag_days",
                    models.IntegerField(
                        default=0,
                        help_text="Positive = lag (delay), Negative = lead (overlap)",
                    ),
                ),
                (
                    "predecessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="successor_deps",
                        to="projects.projecttask",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predecessor_deps",
                        to="projects.projecttask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Dependency",
                "verbose_name_plural": "Task Dependencies",
                "unique_together": {("predecessor", "successor")},
            },
        ),
    ]
