# Generated by Django 5.2.14 on 2026-09-03 05:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_gantt_scheduling_fields_and_task_dependency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GanttImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(db_index=True, max_length=64)),
                ('detected_format', models.CharField(max_length=100)),
                ('selected_sheet', models.CharField(max_length=255)),
                ('staged_data', models.JSONField(default=dict)),
                ('imported_task_ids', models.JSONField(default=list)),
                ('task_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('completed', 'Completed'), ('failed', 'Failed')], default='staged', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gantt_import_batches', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gantt_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='projects_ga_project_139f2a_idx'), models.Index(fields=['uuid', 'status'], name='projects_ga_uuid_b6050f_idx')],
            },
        ),
    ]
