# Generated by Django 5.2.14 on 2026-07-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_phone_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("staff", "Staff"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
