# Generated by Django 5.2.14 on 2026-07-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('manage_roles', 'Can manage user roles and groups')]},
        ),
    ]
