# Generated by Django 5.2.14 on 2026-07-24 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_passwordresetotp"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginProtection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(blank=True, db_index=True, max_length=255)),
                (
                    "ip",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                (
                    "device_fingerprint",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("failed_attempts", models.PositiveIntegerField(default=0)),
                ("current_lock_level", models.PositiveIntegerField(default=0)),
                (
                    "locked_until",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("observation_ends_at", models.DateTimeField(blank=True, null=True)),
                ("captcha_required", models.BooleanField(default=False)),
                ("last_attempt", models.DateTimeField(auto_now=True)),
                ("last_success", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_protections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "login_protection",
                "indexes": [
                    models.Index(
                        fields=["user", "ip", "device_fingerprint"],
                        name="login_prote_user_id_6c3646_idx",
                    ),
                    models.Index(
                        fields=["email", "ip", "device_fingerprint"],
                        name="login_prote_email_bcbd36_idx",
                    ),
                    models.Index(
                        fields=["ip", "device_fingerprint"],
                        name="login_prote_ip_20d02d_idx",
                    ),
                    models.Index(
                        fields=["locked_until"], name="login_prote_locked__9b8548_idx"
                    ),
                ],
            },
        ),
    ]
