# Generated by Django 5.2.14 on 2026-07-24 06:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_loginprotection"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceLockEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
                ("lock_reason", models.CharField(default="idle", max_length=50)),
                ("unlock_method", models.CharField(blank=True, max_length=50)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.usersession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_lock_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workspace_lock_event",
                "ordering": ["-locked_at"],
            },
        ),
    ]
