# Generated by Django 5.2.14 on 2026-07-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_usersecurityprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=50, unique=True)),
                ("mfa_required", models.BooleanField(default=False)),
                (
                    "unlock_method",
                    models.CharField(
                        choices=[
                            ("password", "Password"),
                            ("pin", "PIN"),
                            ("mfa", "MFA TOTP"),
                        ],
                        default="password",
                        max_length=20,
                    ),
                ),
                (
                    "reauth_interval_hours",
                    models.PositiveIntegerField(blank=True, default=4, null=True),
                ),
                ("trusted_device_days", models.PositiveIntegerField(default=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "security_policy",
            },
        ),
        migrations.AddField(
            model_name="usersecurityprofile",
            name="pin_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="usersession",
            name="last_reauth_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
