# Generated by Django 5.2.14 on 2026-07-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_action_module_role_permission_approvalpolicy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('hr', 'HR')], default='staff', max_length=20),
        ),
    ]
