# Generated by Django 5.2.14 on 2026-07-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('hr', 'HR'), ('finance', 'Finance'), ('accounts', 'Accounts')], default='staff', max_length=20),
        ),
    ]
