# Generated by Django 5.2.14 on 2026-07-25 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="securitypolicy",
            name="idle_timeout_minutes",
            field=models.PositiveIntegerField(
                default=30,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(240),
                ],
            ),
        ),
    ]
