# Generated by Django 5.2.14 on 2026-07-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_securitypolicy_idle_timeout_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersecurityprofile",
            name="workspace_password_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="securitypolicy",
            name="unlock_method",
            field=models.CharField(
                choices=[
                    ("password", "Password"),
                    ("pin", "PIN"),
                    ("workspace_password", "Dedicated Workspace Password"),
                    ("mfa", "MFA TOTP"),
                ],
                default="password",
                max_length=20,
            ),
        ),
    ]
