/**
 * FieldTrack Design System — Tailwind Config
 * Flatter radii & locked tokens
 */

module.exports = {
    darkMode: 'class',
    content: [
        'templates/**/*.html',
        'apps/**/*.py',
        'fieldtrack/**/*.py',
        'static/**/*.js',
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: [
                    'Inter',
                    'Noto Sans Bengali',
                    'system-ui',
                    '-apple-system',
                    'sans-serif',
                ],
            },
            fontSize: {
                'large-title': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
                'page-title': ['24px', { lineHeight: '1.25', fontWeight: '700' }],
                'section-title': ['20px', { lineHeight: '1.3', fontWeight: '700' }],
                'card-title': ['18px', { lineHeight: '1.35', fontWeight: '600' }],
                'body': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
                'small': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
                'caption': ['11px', { lineHeight: '1.4', fontWeight: '400' }],
                'tiny': ['10px', { lineHeight: '1.3', fontWeight: '400' }],
            },
            colors: {
                primary: {
                    DEFAULT: '#1877F2',
                    hover: '#166FE5',
                    50:  '#F4FAFF',
                    100: '#E7F3FF',
                    200: '#CDE5FF',
                    300: '#A8D1FF',
                    400: '#5FAAFF',
                    500: '#1877F2',
                    600: '#166FE5',
                    700: '#1455B0',
                    800: '#083E89',
                    900: '#00193D',
                },
                'primary-hover': '#166FE5',
                bg: '#F0F2F5',
                surface: '#FFFFFF',
                'sidebar-dark': '#243746',
                text: {
                    DEFAULT: '#1C1E21',
                    secondary: '#65676B',
                    muted: '#8A8D91',
                },
                border: {
                    DEFAULT: '#E4E6EB',
                    card: '#E4E6EB',
                    input: '#DADDE1',
                },
                success: '#31A24C',
                warning: '#F7B928',
                danger: '#E41E3F',
                accent: {
                    50:  '#E7F6EA',
                    100: '#D1F0D9',
                    200: '#A3E1B3',
                    300: '#75CE8D',
                    400: '#47BC67',
                    500: '#31A24C',
                    600: '#2B8E42',
                    700: '#216D33',
                    800: '#174B23',
                    900: '#0B2712',
                },
            },
            spacing: {
                '1': '4px',
                '2': '8px',
                '3': '12px',
                '4': '16px',
                '5': '20px',
                '6': '24px',
                '8': '32px',
                '10': '40px',
                '12': '48px',
                '16': '64px',
                'sidebar-w': '280px',
                'sidebar-w-collapsed': '56px',
                'topbar-h': '56px',
            },
            borderRadius: {
                'btn':    '4px',
                'input':  '4px',
                'card':   '6px',
                'modal':  '8px',
                'dialog': '8px',
                'drawer': '8px',
                'chip':   '4px',
                'avatar': '999px',
            },
            boxShadow: {
                'sm':       '0 1px 2px rgba(0,0,0,.05)',
                'md':       '0 2px 8px rgba(0,0,0,.12)',
                'lg':       '0 8px 24px rgba(0,0,0,.15)',
                'soft':     '0 1px 2px rgba(0,0,0,.05)',
                'dropdown': '0 2px 8px rgba(0,0,0,.12)',
                'elevated': '0 8px 24px rgba(0,0,0,.15)',
                'none-dark': '0 0 0 1px rgba(255,255,255,0.06)',
            },
            transitionDuration: {
                DEFAULT: '180ms',
                '180': '180ms',
            },
            transitionTimingFunction: {
                DEFAULT: 'ease',
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
        require('@tailwindcss/aspect-ratio'),
    ],
}
