# Generated by Django 5.2.14 on 2026-05-20 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('service_account_json', models.TextField(blank=True, help_text='Paste Google Service Account JSON key here')),
                ('folder_id', models.CharField(blank=True, help_text='Google Drive folder ID for backups', max_length=255)),
                ('auto_daily_enabled', models.BooleanField(default=False, help_text='Run backup every day at 2 AM')),
                ('auto_3day_enabled', models.BooleanField(default=False, help_text='Run backup every 3 days')),
                ('auto_upload_to_drive', models.BooleanField(default=False, help_text='Auto upload backups to Google Drive')),
                ('keep_local_copies', models.IntegerField(default=7, help_text='Keep this many local backup files')),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Drive Config',
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('auto_daily', 'Auto Daily'), ('auto_3day', 'Auto Every 3 Days')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0, help_text='Size in bytes')),
                ('record_count', models.IntegerField(default=0)),
                ('gdrive_uploaded', models.BooleanField(default=False)),
                ('gdrive_file_id', models.CharField(blank=True, max_length=255)),
                ('gdrive_link', models.URLField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
