# Generated by Django 5.2.14 on 2026-07-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googledriveconfig',
            options={'permissions': [('run_backup', 'Can run manual backup')], 'verbose_name': 'Google Drive Config'},
        ),
    ]
