# Generated by Django 5.2.14 on 2026-07-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0002_alter_googledriveconfig_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="backuprecord",
            name="is_encrypted",
            field=models.BooleanField(
                default=False,
                help_text="Whether the on-disk backup file is Fernet-encrypted",
            ),
        ),
        migrations.AddField(
            model_name="googledriveconfig",
            name="encryption_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Encrypt backup files at rest using a server-bound Fernet key",
            ),
        ),
        migrations.AddField(
            model_name="googledriveconfig",
            name="master_key_wrapped",
            field=models.TextField(
                blank=True,
                help_text="Base64-encoded Fernet key wrapped with a KEK derived from SECRET_KEY. Never stores the raw key. Set via 'Generate Key' action.",
            ),
        ),
    ]
