# Generated by Django 5.2.14 on 2026-10-04 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenanttestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=50)),
                ('time_format', models.CharField(default='24h', max_length=20)),
                ('currency', models.CharField(default='BDT', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company_configuration', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Company Configuration',
                'verbose_name_plural': 'Company Configurations',
            },
        ),
    ]
