# Generated by Django 5.2.14 on 2026-07-25 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique identifier e.g. LEAVE_APPROVAL",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="Target module e.g. leave, expense", max_length=50
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workflow_definition",
                "ordering": ["module", "code"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowDelegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workflow_code",
                    models.CharField(
                        blank=True, help_text="Empty means all workflows", max_length=50
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workflow_delegation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        help_text="Model type e.g. leave_request, expense_claim",
                        max_length=50,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        help_text="Primary key of target object", max_length=50
                    ),
                ),
                ("current_step", models.PositiveIntegerField(default=1)),
                ("current_status", models.CharField(default="pending", max_length=50)),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("sla_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="workflow.workflowdefinition",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workflow_instance",
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.PositiveIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "Submit"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("return", "Return"),
                            ("delegate", "Delegate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegated_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="workflow.workflowinstance",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_action",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("from_status", models.CharField(max_length=50)),
                ("to_status", models.CharField(max_length=50)),
                (
                    "approver_role",
                    models.CharField(
                        blank=True,
                        default="manager",
                        help_text="Static config role for approval",
                        max_length=50,
                    ),
                ),
                (
                    "sla_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Static config SLA hours for step completion",
                        null=True,
                    ),
                ),
                ("escalation_role", models.CharField(blank=True, max_length=50)),
                ("allow_return", models.BooleanField(default=True)),
                ("allow_rejection", models.BooleanField(default=True)),
                ("notification_triggers", models.JSONField(blank=True, default=dict)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="workflow.workflowdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_step",
                "ordering": ["workflow", "step_number"],
                "unique_together": {("workflow", "step_number")},
            },
        ),
    ]
