# Generated by Django 5.2.14 on 2026-07-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="approver_resolution_type",
            field=models.CharField(
                choices=[
                    ("static_role", "Static Role"),
                    ("reporting_manager", "Reporting Manager"),
                ],
                default="static_role",
                help_text="Whether to resolve approver by static role or dynamic reporting manager",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workflowaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("submit", "Submit"),
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("return", "Return"),
                    ("delegate", "Delegate"),
                    ("cancel", "Cancel"),
                ],
                max_length=20,
            ),
        ),
    ]
