# Generated by Django 5.2.14 on 2026-07-17 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0009_employeedocument"),
        ("projects", "0012_project_client_email_project_consultant_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField()),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Leave blank for all-day events",
                        null=True,
                    ),
                ),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("Meeting", "Meeting"),
                            ("Task Deadline", "Task Deadline"),
                            ("Site Visit", "Site Visit"),
                            ("Reminder", "Reminder"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="schedule_events",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_schedule_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_events",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time", "title"],
            },
        ),
    ]
