# Generated by Django 6.0.7 on 2026-08-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleevent",
            name="version",
            field=models.IntegerField(default=1),
        ),
    ]
