# Generated by Django 5.2.14 on 2026-10-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_add_event_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
