# Generated by Django 5.2.14 on 2026-07-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetype",
            name="category",
            field=models.CharField(
                choices=[("sick", "Sick"), ("casual", "Casual"), ("other", "Other")],
                default="other",
                max_length=20,
            ),
        ),
    ]
