# Generated by Django 5.2.14 on 2026-07-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0002_leavetype_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetype",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Set as default leave type for automated absence deductions",
            ),
        ),
    ]
