# Generated by Django 5.2.14 on 2026-07-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leavetype_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-requested_at'], 'permissions': [('approve_leaverequest', 'Can approve or reject leave requests')]},
        ),
    ]
