# Generated by Django 5.2.14 on 2026-07-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0006_alter_leaverequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("manager_approved", "Manager Approved"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("returned", "Returned"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
