# Generated by Django 5.2.14 on 2026-09-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0007_alter_leaverequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="number_of_days",
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
