# Generated by Django 5.2.14 on 2026-09-01 12:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_leavetype_is_active_alter_leaverequest_number_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='deduction_percent',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Percentage of pay to deduct for leave under this type (0=fully paid, 100=fully unpaid)',
                max_digits=5,
            ),
        ),
    ]
