# Generated by Django 5.1.4 on 2026-05-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="attendance_type",
            field=models.CharField(
                choices=[
                    ("check_in", "Check In"),
                    ("check_out", "Check Out"),
                    ("field_visit", "Field Visit"),
                ],
                default="check_in",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="client_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="attendance",
            name="site_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="attendance",
            name="visit_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
