# Generated by Django 5.1.4 on 2026-05-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0002_attendance_attendance_type_attendance_client_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="attendance/photos/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="attendancelocation",
            name="event_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="attendance/photos/%Y/%m/%d/"
            ),
        ),
    ]
