# Generated by Django 5.1.4 on 2026-05-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_attendance_photo_attendancelocation_event_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="client_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="site_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="visit_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
