# Generated by Django 5.1.4 on 2026-05-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_alter_attendance_client_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date", "-check_in_time"]},
        ),
        migrations.AlterField(
            model_name="attendance",
            name="attendance_type",
            field=models.CharField(
                choices=[
                    ("check_in", "Check In/Out Session"),
                    ("field_visit", "Field Visit"),
                ],
                default="check_in",
                max_length=20,
            ),
        ),
    ]
