# Generated by Django 5.2.14 on 2026-05-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_is_early_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelocation',
            name='event',
            field=models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('auto_track', 'Auto Track')], max_length=20),
        ),
    ]
