# Generated by Django 5.2.14 on 2026-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendancelocation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='expired_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked expired', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_expired',
            field=models.BooleanField(default=False, help_text='Data older than 3 months'),
        ),
        migrations.AddField(
            model_name='attendancelocation',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
