# Generated by Django 5.2.14 on 2026-05-21 11:14

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_expired_at_attendance_is_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='attendance/photos/%Y/%m/%d/'),
        ),
    ]
