# Generated by Django 5.2.14 on 2026-07-12 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_alter_attendance_photo"),
        ("employees", "0005_alter_employeeprofile_branch_and_more"),
        ("leave", "0002_leavetype_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceAbsentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absent_logs",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "leave_type_deducted",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leave.leavetype",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "date")},
            },
        ),
    ]
