# Generated by Django 5.2.14 on 2026-07-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_attendance_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_expired',
            field=models.BooleanField(db_index=True, default=False, help_text='Data older than 3 months'),
        ),
    ]
