# Generated by Django 5.2.14 on 2026-07-19 07:57

import django.db.models.deletion
import uuid
from django.db import migrations, models

def gen_uuids_attendance(apps, schema_editor):
    MyModel = apps.get_model('attendance', 'Attendance')
    for row in MyModel.objects.filter(sync_uuid__isnull=True):
        row.sync_uuid = uuid.uuid4()
        row.save(update_fields=['sync_uuid'])

def gen_uuids_location(apps, schema_editor):
    MyModel = apps.get_model('attendance', 'AttendanceLocation')
    for row in MyModel.objects.filter(sync_uuid__isnull=True):
        row.sync_uuid = uuid.uuid4()
        row.save(update_fields=['sync_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_attendance_date_alter_attendance_is_expired'),
        ('employees', '0012_employeelocationsync_client_event_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='client_event_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sync_uuid',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuids_attendance, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='attendance',
            name='sync_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelocation',
            name='client_event_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelocation',
            name='sync_uuid',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuids_location, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='attendancelocation',
            name='sync_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='attendancelocation',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_batch_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('records_total', models.PositiveIntegerField()),
                ('records_success', models.PositiveIntegerField()),
                ('records_failed', models.PositiveIntegerField()),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='employees.employeeprofile')),
            ],
        ),
    ]
