# Generated by Django 5.2.14 on 2026-07-24 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0013_attendance_client_event_time_attendance_sync_uuid_and_more",
        ),
        ("branches", "0003_holiday"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="ot_status",
            field=models.CharField(
                choices=[
                    ("none", "No Overtime"),
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("absent", "Absent"),
                    ("holiday_attendance", "Holiday Attendance"),
                ],
                default="on_time",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AttendanceAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("old_check_in_time", models.DateTimeField(blank=True, null=True)),
                ("old_check_out_time", models.DateTimeField(blank=True, null=True)),
                ("old_status", models.CharField(blank=True, max_length=20, null=True)),
                ("new_check_in_time", models.DateTimeField(blank=True, null=True)),
                ("new_check_out_time", models.DateTimeField(blank=True, null=True)),
                ("new_status", models.CharField(blank=True, max_length=20, null=True)),
                ("reason", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="attendance.attendance",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceCorrectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="attendance_corrections/"
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correction_requests",
                        to="attendance.attendance",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendancePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo_required", models.BooleanField(default=True)),
                (
                    "geofencing_policy",
                    models.CharField(
                        choices=[
                            ("disabled", "Disabled"),
                            ("warning", "Warning Only"),
                            ("block", "Block Check-in"),
                        ],
                        default="warning",
                        max_length=20,
                    ),
                ),
                (
                    "branch",
                    models.OneToOneField(
                        blank=True,
                        help_text="If null, this is the global default policy",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_policy",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Attendance Policies",
            },
        ),
        migrations.CreateModel(
            name="ForgotCheckoutRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_manager", "Pending Manager Approval"),
                            ("pending_hr", "Pending HR Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_manager",
                        max_length=20,
                    ),
                ),
                ("check_out_time", models.DateTimeField()),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forgot_checkout_requests",
                        to="attendance.attendance",
                    ),
                ),
                (
                    "reviewed_by_hr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_forgot_checkouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager_forgot_checkouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
    ]
