# Generated by Django 5.2.14 on 2026-07-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_attendanceactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='allow_holiday_attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='allow_outside_geofence',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='gps_required',
            field=models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('warn_only', 'Warn Only')], default='required', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='late_grace_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='max_gps_accuracy_meters',
            field=models.IntegerField(default=100),
        ),
    ]
