# Generated by Django 5.2.14 on 2026-07-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_attendancepolicy_allow_holiday_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_policy_exception',
            field=models.BooleanField(default=False),
        ),
    ]
