# Generated by Django 5.2.14 on 2026-07-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_attendance_is_policy_exception'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='gps_quality',
            field=models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('missing', 'Missing')], default='good', max_length=10),
        ),
    ]
