# Generated by Django 5.2.14 on 2026-09-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_attendance_gps_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_outside_geofence',
            field=models.BooleanField(db_index=True, default=False, help_text='Flagged when check-in occurred outside permitted geofence radius'),
        ),
    ]
