# Generated by Django 5.2.14 on 2026-08-14 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0003_holiday"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("employees", "0027_employee_is_trashed_employee_trashed_at"),
        ("projects", "0023_gantt_scheduling_fields_and_task_dependency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_role", models.CharField(blank=True, max_length=64)),
                ("module", models.CharField(db_index=True, max_length=100)),
                ("object_type", models.CharField(db_index=True, max_length=100)),
                ("object_id", models.CharField(db_index=True, max_length=100)),
                ("object_label", models.CharField(blank=True, max_length=255)),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("before_data", models.JSONField(blank=True, default=dict)),
                ("after_data", models.JSONField(blank=True, default=dict)),
                ("changed_fields", models.JSONField(blank=True, default=dict)),
                ("request_path", models.CharField(blank=True, max_length=255)),
                ("request_method", models.CharField(blank=True, max_length=20)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("session_device", models.CharField(blank=True, max_length=255)),
                ("reason_note", models.TextField(blank=True)),
                (
                    "content_object_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "related_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="branches.branch",
                    ),
                ),
                (
                    "related_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="employees.employee",
                    ),
                ),
                (
                    "related_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("session_device", models.CharField(blank=True, max_length=255)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "audit_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="audit.auditevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="TrashEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(db_index=True, max_length=100)),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(db_index=True, max_length=100)),
                ("object_label", models.CharField(blank=True, max_length=255)),
                (
                    "content_object_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("delete_reason", models.TextField(blank=True)),
                ("restore_allowed", models.BooleanField(default=True)),
                ("permanent_delete_allowed", models.BooleanField(default=True)),
                ("dependency_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("restored", "Restored"),
                            ("permanently_deleted", "Permanently Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=32,
                    ),
                ),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("permanently_deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trash_entries_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permanently_deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trash_entries_purged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trash_entries",
                        to="branches.branch",
                    ),
                ),
                (
                    "related_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trash_entries",
                        to="employees.employee",
                    ),
                ),
                (
                    "related_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trash_entries",
                        to="projects.project",
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trash_entries_restored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-deleted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["module", "created_at"], name="audit_audit_module_8d996c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["action", "created_at"], name="audit_audit_action_0c0ad1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["object_type", "object_id", "created_at"],
                name="audit_audit_object__4aa284_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trashentry",
            index=models.Index(
                fields=["module", "status", "deleted_at"],
                name="audit_trash_module_c0394e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trashentry",
            index=models.Index(
                fields=["deleted_by", "deleted_at"],
                name="audit_trash_deleted_55e479_idx",
            ),
        ),
    ]
