# Generated by Django 5.2.14 on 2026-08-14 10:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_pinnedmenuitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="local", max_length=50)),
                ("provider_file_id", models.CharField(blank=True, max_length=255)),
                ("original_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("original_size", models.PositiveIntegerField()),
                ("optimized_size", models.PositiveIntegerField(blank=True, null=True)),
                ("checksum", models.CharField(db_index=True, max_length=64)),
                ("url_path", models.CharField(max_length=1024)),
                ("module", models.CharField(blank=True, max_length=100)),
                ("object_type", models.CharField(blank=True, max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=100)),
                ("is_private", models.BooleanField(default=False)),
                ("status", models.CharField(default="active", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["checksum"], name="audit_media_checksu_96cab2_idx"
                    ),
                    models.Index(
                        fields=["module", "object_type", "object_id"],
                        name="audit_media_module_720e3a_idx",
                    ),
                ],
            },
        ),
    ]
