# Generated by Django 5.2.14 on 2026-08-14 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_mediaasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
