# Generated by Django 5.2.14 on 2026-09-04 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AISetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        default="You are FieldTrack AI Assistant, the intelligent workforce and operational analytics copilot for the FieldTrack workforce platform. Provide accurate, professional, concise, and truthful insights based on the provided operational records. Answer directly in 2 to 4 sentences.",
                        help_text="Custom system instructions or persona guiding the AI's responses.",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.3,
                        help_text="Sampling temperature (0.0 = deterministic/focused, 1.0 = creative).",
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        default=800, help_text="Maximum tokens per AI response."
                    ),
                ),
                (
                    "include_operational_context",
                    models.BooleanField(
                        default=True,
                        help_text="Inject allowlisted, read-only RBAC operational database metrics into queries.",
                    ),
                ),
                (
                    "primary_provider",
                    models.CharField(
                        choices=[
                            ("gemini", "Google Gemini"),
                            ("openai", "OpenAI (GPT-4o / GPT-4o-mini)"),
                            ("groq", "Groq (Llama / Mixtral)"),
                            ("anthropic", "Anthropic Claude"),
                            ("openrouter", "OpenRouter (Universal)"),
                        ],
                        default="gemini",
                        max_length=50,
                    ),
                ),
                (
                    "primary_model",
                    models.CharField(
                        default="gemini-2.5-flash",
                        help_text="Model identifier (e.g. gemini-2.5-flash, gpt-4o-mini, llama-3.3-70b-versatile)",
                        max_length=100,
                    ),
                ),
                (
                    "primary_api_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Primary API key. If empty, falls back to server environment variables.",
                        max_length=255,
                    ),
                ),
                (
                    "fallback_configs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of ordered fallback providers and keys invoked when the primary fails.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_settings_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Setting",
                "verbose_name_plural": "AI Settings",
            },
        ),
    ]
