# Generated by Django 6.0.7 on 2026-08-13 21:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeepayrollcalculation",
            name="source_total_approved_leave_days",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="employeepayrollcalculation",
            name="source_total_approved_ot_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="employeepayrollcalculation",
            name="source_total_present_days",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="employeepayrollcalculation",
            name="synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
