# Generated by Django 5.2.14 on 2026-09-01 12:07

from decimal import Decimal
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('payroll', '0003_payrolladjustment_payrollworkflowaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_divisor_mode', models.CharField(choices=[('fixed_30', 'Fixed 30'), ('calendar_days', 'Calendar Days'), ('working_days', 'Working Days')], default='fixed_30', max_length=20)),
                ('default_ot_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(blank=True, help_text='Branch for this policy. Null represents company-wide default.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_policy', to='branches.branch')),
            ],
        ),
    ]
