# Generated by Django 5.2.14 on 2026-09-06 05:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payrollpolicy'),
        ('tenants', '0003_tenanttestmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='configuration_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Immutable snapshot of the configuration at the time of calculation/finalization'),
        ),
        migrations.CreateModel(
            name='PayrollConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('pay_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Bi-Weekly'), ('weekly', 'Weekly')], default='monthly', max_length=20)),
                ('payroll_period_type', models.CharField(choices=[('calendar_month', 'Calendar Month'), ('custom_cycle', 'Custom Cutoff Cycle')], default='calendar_month', max_length=30)),
                ('cutoff_day', models.PositiveIntegerField(default=25, help_text='Day of the month for attendance cutoff (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('payment_day', models.PositiveIntegerField(default=30, help_text='Day of the month for salary disbursement (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('working_day_basis', models.CharField(choices=[('fixed_30', 'Fixed 30'), ('calendar_days', 'Calendar Days'), ('working_days', 'Working Days')], default='fixed_30', help_text='Divisor basis for salary absence and proration calculations', max_length=20)),
                ('attendance_source', models.CharField(default='attendance.AttendanceRecord', help_text='Data source identifier for employee attendance logs', max_length=100)),
                ('leave_source', models.CharField(default='leave.LeaveRequest', help_text='Data source identifier for approved employee leaves', max_length=100)),
                ('overtime_source', models.CharField(default='attendance.AttendanceRecord', help_text='Data source identifier for approved employee overtime', max_length=100)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4)),
                ('proration_method', models.CharField(choices=[('calendar_days', 'Calendar Days Basis'), ('working_days', 'Working Days Basis'), ('none', 'No Proration')], default='calendar_days', max_length=30)),
                ('rounding_rule', models.CharField(choices=[('nearest_integer', 'Round to Nearest Integer (Half Up)'), ('round_up', 'Round Up (Ceiling)'), ('round_down', 'Round Down (Floor)'), ('two_decimal', 'Preserve Two Decimals')], default='nearest_integer', max_length=30)),
                ('negative_net_pay_policy', models.CharField(choices=[('zero_out', 'Zero Out and Carry Forward'), ('prevent_finalize', 'Prevent Finalization if Negative'), ('allow_negative', 'Allow Negative Net Pay')], default='zero_out', max_length=30)),
                ('approval_workflow_steps', models.PositiveIntegerField(choices=[(1, 'Single-Step (Direct Approve)'), (2, 'Two-Step (Review then Approve)')], default=2, help_text='Number of workflow approval steps required')),
                ('payslip_prefix', models.CharField(default='PSL-', help_text='Prefix used in generated payslip numbers', max_length=20)),
                ('supported_payment_methods', models.JSONField(default=list, help_text="Supported payment methods, e.g. ['bank', 'cash', 'split']")),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_configs_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_configs_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='configuration',
            field=models.ForeignKey(blank=True, help_text='Configuration version snapshot used for this payroll run', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='payroll.payrollconfiguration'),
        ),
        migrations.AddIndex(
            model_name='payrollconfiguration',
            index=models.Index(fields=['tenant', 'is_active'], name='payroll_pay_tenant__da3476_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollconfiguration',
            index=models.Index(fields=['tenant', 'version'], name='payroll_pay_tenant__3c175a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollconfiguration',
            unique_together={('tenant', 'version')},
        ),
    ]
