# Generated by Django 5.2.14 on 2026-09-06 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_alter_employee_payment_method'),
        ('payroll', '0005_payrollrun_configuration_snapshot_and_more'),
        ('tenants', '0003_tenanttestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayrollcalculation',
            name='payment_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Immutable snapshot of employee payment destination at calculation time'),
        ),
        migrations.CreateModel(
            name='PayrollPaymentDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('bank', 'Bank Transfer'), ('cash', 'Cash'), ('mfs', 'Mobile Financial Service')], db_index=True, default='bank', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('branch_name', models.CharField(blank=True, max_length=150)),
                ('account_holder_name', models.CharField(blank=True, max_length=255)),
                ('account_number_encrypted', models.TextField(blank=True, help_text='Encrypted bank account number')),
                ('account_number_last4', models.CharField(blank=True, db_index=True, max_length=4)),
                ('routing_number', models.CharField(blank=True, db_index=True, max_length=9)),
                ('mfs_provider', models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket')], db_index=True, max_length=20)),
                ('wallet_number_encrypted', models.TextField(blank=True, help_text='Encrypted mobile wallet number')),
                ('wallet_number_last4', models.CharField(blank=True, db_index=True, max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_destinations', to='employees.bank')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_destinations', to='employees.bankbranch')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_destination', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Payment Destination',
                'verbose_name_plural': 'Payroll Payment Destinations',
                'indexes': [models.Index(fields=['tenant', 'payment_type'], name='payroll_pay_tenant__c63c64_idx'), models.Index(fields=['tenant', 'is_active'], name='payroll_pay_tenant__c5da62_idx')],
            },
        ),
    ]
