# Generated by Django 5.2.14 on 2026-05-20 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_start_time', models.TimeField(default='09:00', help_text='Office opening time')),
                ('office_end_time', models.TimeField(default='18:00', help_text='Office closing time')),
                ('late_after_minutes', models.IntegerField(default=15, help_text='Minutes after start time = Late')),
                ('early_checkout_before_minutes', models.IntegerField(default=30, help_text='Minutes before end time = Early checkout')),
                ('overtime_after_minutes', models.IntegerField(default=0, help_text='Minutes after end time = Overtime starts')),
                ('working_days', models.JSONField(default=list, help_text='List of working day names')),
                ('tracking_interval_minutes', models.IntegerField(default=10, help_text='How often to track location after check-in')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='branches.branch')),
            ],
        ),
    ]
