# Generated by Django 5.1.4 on 2026-05-19 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="tracking_interval",
            field=models.IntegerField(
                choices=[
                    (0, "Disabled"),
                    (5, "Every 5 minutes"),
                    (10, "Every 10 minutes"),
                    (15, "Every 15 minutes"),
                    (30, "Every 30 minutes"),
                    (60, "Every 1 hour"),
                ],
                default=0,
                help_text="How often (minutes) to auto-sync location when employee is checked in. 0 = disabled.",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeLocationSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("accuracy", models.FloatField(default=0)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_syncs",
                        to="employees.employeeprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
