# Generated by Django 5.2.14 on 2026-05-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeprofile_tracking_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='overtime_enabled',
            field=models.BooleanField(default=False, help_text='Enable overtime tracking for this employee'),
        ),
    ]
