# Generated by Django 5.2.14 on 2026-05-21 11:14

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeeprofile_overtime_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='profile_photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='employees/photos/'),
        ),
    ]
