# Generated by Django 5.2.14 on 2026-06-05 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_officeschedule"),
        ("employees", "0004_alter_employeeprofile_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="branches.branch",
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
