# Generated by Django 5.2.14 on 2026-07-12 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_alter_employeeprofile_branch_and_more"),
        ("leave", "0002_leavetype_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeLeaveRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days_per_year", models.IntegerField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_rules",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leave.leavetype",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "leave_type")},
            },
        ),
    ]
