# Generated by Django 5.2.14 on 2026-07-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_employeeleaverule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="tracking_interval",
            field=models.IntegerField(
                choices=[
                    (0, "Disabled"),
                    (5, "Every 5 minutes"),
                    (10, "Every 10 minutes"),
                    (15, "Every 15 minutes"),
                    (30, "Every 30 minutes"),
                    (60, "Every 1 hour"),
                    (90, "Every 1.5 hours"),
                    (120, "Every 2 hours"),
                ],
                default=0,
                help_text="How often (minutes) to auto-sync location when employee is checked in. 0 = disabled.",
            ),
        ),
    ]
