# Generated by Django 5.2.14 on 2026-07-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employeeprofile_tracking_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelocationsync',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
