# Generated by Django 5.2.14 on 2026-07-17 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0008_alter_employeelocationsync_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_type", models.CharField(max_length=100)),
                ("expiry_date", models.DateField()),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="employees/documents/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="employees.employeeprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date"],
            },
        ),
    ]
