# Generated by Django 5.2.14 on 2026-07-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employeedocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'permissions': [('view_reports', 'Can view analytical reports')]},
        ),
    ]
