# Generated by Django 5.2.14 on 2026-07-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0010_alter_employeeprofile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="is_project_manager",
            field=models.BooleanField(
                default=False,
                help_text="Allow this employee to work as a Project Manager and manage projects",
            ),
        ),
    ]
