# Generated by Django 5.2.14 on 2026-07-19 07:57

import uuid
from django.db import migrations, models

def gen_uuids(apps, schema_editor):
    MyModel = apps.get_model('employees', 'EmployeeLocationSync')
    for row in MyModel.objects.filter(sync_uuid__isnull=True):
        row.sync_uuid = uuid.uuid4()
        row.save(update_fields=['sync_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employeeprofile_is_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelocationsync',
            name='client_event_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeelocationsync',
            name='sync_uuid',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='employeelocationsync',
            name='sync_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='employeelocationsync',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
