# Generated by Django 5.2.14 on 2026-07-24 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employees",
            "0013_department_designation_employee_employmenthistory_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="master_employee",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_profile",
                to="employees.employee",
            ),
        ),
    ]
