# Generated by Django 5.2.14 on 2026-07-24 07:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0014_employeeprofile_master_employee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("laptop", "Laptop"),
                            ("mobile", "Mobile Phone"),
                            ("sim", "SIM Card"),
                            ("tablet", "Tablet"),
                            ("token", "Security Token / Dongle"),
                            ("other", "Other Asset"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "asset_tag",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=150)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "Brand New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("damaged", "Damaged / Needs Repair"),
                        ],
                        default="good",
                        max_length=30,
                    ),
                ),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["asset_tag"],
            },
        ),
        migrations.AlterModelOptions(
            name="employeedocument",
            options={"ordering": ["-is_active", "-version", "-uploaded_at"]},
        ),
        migrations.RenameField(
            model_name="employeedocument",
            old_name="created_at",
            new_name="uploaded_at",
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="employee_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="employeedocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("nid", "National ID (NID)"),
                    ("passport", "Passport"),
                    ("photo", "Profile Photo"),
                    ("resume", "Resume / CV"),
                    ("appointment_letter", "Appointment Letter"),
                    ("contract", "Employment Contract"),
                    ("education", "Education Certificate"),
                    ("certificate", "Professional Certificate"),
                    ("medical", "Medical Report"),
                    ("police_clearance", "Police Clearance"),
                    ("other", "Other Document"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="employeedocument",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="employees.employeeprofile",
            ),
        ),
        migrations.AlterField(
            model_name="employeedocument",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AssetAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateField(default=django.utils.timezone.now)),
                ("returned_date", models.DateField(blank=True, null=True)),
                (
                    "condition_at_assignment",
                    models.CharField(
                        choices=[
                            ("new", "Brand New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("damaged", "Damaged / Needs Repair"),
                        ],
                        default="good",
                        max_length=30,
                    ),
                ),
                (
                    "condition_at_return",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "Brand New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("damaged", "Damaged / Needs Repair"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="employees.asset",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_assignments",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_date"],
            },
        ),
        migrations.CreateModel(
            name="DocumentDownloadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_logs",
                        to="employees.employeedocument",
                    ),
                ),
                (
                    "downloaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-downloaded_at"],
            },
        ),
    ]
