# Generated by Django 5.2.14 on 2026-07-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0016_lifecycle_transition_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="bank_account",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="basic_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="data_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("branch", "Branch Level"),
                    ("department", "Department Level"),
                    ("global", "Global / Organization Wide"),
                ],
                default="branch",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_relation",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                    ("intern", "Intern"),
                    ("probationary", "Probationary"),
                ],
                default="full_time",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="mfa_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="overtime_policy",
            field=models.CharField(
                blank=True, default="Standard Overtime (1.5x)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bank", "Bank Transfer"),
                    ("cash", "Cash"),
                    ("mobile", "Mobile Banking"),
                ],
                default="bank",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="pf_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="salary_structure",
            field=models.CharField(
                blank=True, default="Standard Salary Structure", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="shift",
            field=models.CharField(blank=True, default="Day Shift", max_length=50),
        ),
        migrations.AddField(
            model_name="employee",
            name="tax_profile",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="weekly_holiday_policy",
            field=models.CharField(
                blank=True, default="Friday, Saturday", max_length=100
            ),
        ),
    ]
