# Generated by Django 5.2.14 on 2026-07-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0017_employee_bank_account_employee_bank_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_suspended",
            field=models.BooleanField(default=False),
        ),
    ]
