# Generated by Django 5.2.14 on 2026-07-24 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0020_employeeauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetassignment",
            name="reassigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reassigned_from",
                to="employees.assetassignment",
            ),
        ),
    ]
