# Generated by Django 5.2.14 on 2026-07-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_employeedocument_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('probation', 'Probation'), ('confirmed', 'Confirmed'), ('transferred', 'Transferred'), ('promoted', 'Promoted'), ('demoted', 'Demoted'), ('notice_period', 'Notice Period'), ('resigned', 'Resigned'), ('terminated', 'Terminated'), ('retired', 'Retired'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='draft', max_length=30),
        ),
    ]
