# Generated by Django 5.2.14 on 2026-08-14 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0025_add_uuid_to_employee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("probation", "Probation"),
                    ("confirmed", "Confirmed"),
                    ("transferred", "Transferred"),
                    ("promoted", "Promoted"),
                    ("demoted", "Demoted"),
                    ("notice_period", "Notice Period"),
                    ("resigned", "Resigned"),
                    ("terminated", "Terminated"),
                    ("retired", "Retired"),
                    ("suspended", "Suspended"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="EmployeeSuspension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suspension_start_date", models.DateField()),
                ("suspension_end_date", models.DateField(blank=True, null=True)),
                ("suspension_reason", models.TextField()),
                ("auto_reactivate", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("previous_status", models.CharField(max_length=30)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspensions",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
    ]
