# Generated by Django 5.2.14 on 2026-08-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0026_alter_employee_status_employeesuspension"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_trashed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="trashed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
