# Generated by Django 5.2.14 on 2026-08-14 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0003_holiday"),
        ("employees", "0027_employee_is_trashed_employee_trashed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="branches",
            field=models.ManyToManyField(
                blank=True, related_name="departments", to="branches.branch"
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="is_global",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="designation",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designations",
                to="employees.department",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="designation",
            name="code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="designation",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
