# Generated by Django 6.0.7 on 2026-09-05 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0028_branch_dept_desig_hierarchy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Stable canonical identifier (e.g. DBBL, BRAC, CITY)",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official institution name registered with Bangladesh Bank",
                        max_length=150,
                        unique=True,
                    ),
                ),
                ("short_name", models.CharField(blank=True, max_length=50)),
                (
                    "bank_type",
                    models.CharField(
                        choices=[
                            ("commercial", "Scheduled Commercial Bank"),
                            ("islamic", "Islamic Shariah-Based Bank"),
                            ("state_owned", "State-Owned Commercial Bank"),
                            ("specialized", "Specialized Development Bank"),
                            ("foreign", "Foreign Commercial Bank"),
                        ],
                        default="commercial",
                        max_length=30,
                    ),
                ),
                (
                    "logo",
                    models.CharField(
                        default="images/banks/default_bank.svg",
                        help_text="Relative static path to local SVG/PNG logo asset",
                        max_length=255,
                    ),
                ),
                ("swift_code", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "source_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Originating authority metadata (e.g. Bangladesh Bank directory release)",
                    ),
                ),
                ("display_order", models.IntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bank Directory",
                "verbose_name_plural": "Bank Directories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BankBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Branch name", max_length=150)),
                ("branch_code", models.CharField(blank=True, max_length=30)),
                (
                    "routing_number",
                    models.CharField(
                        db_index=True,
                        help_text="9-digit Bangladesh Bank canonical routing number",
                        max_length=9,
                    ),
                ),
                ("district", models.CharField(db_index=True, max_length=100)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                ("display_order", models.IntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="employees.bank",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Branch",
                "verbose_name_plural": "Bank Branches",
                "ordering": ["district", "name"],
                "unique_together": {("bank", "routing_number")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_holder_name", models.CharField(max_length=255)),
                (
                    "account_number_encrypted",
                    models.TextField(help_text="Fernet encrypted bank account number"),
                ),
                ("account_number_last4", models.CharField(db_index=True, max_length=4)),
                (
                    "routing_number",
                    models.CharField(
                        db_index=True,
                        help_text="Canonical branch routing number",
                        max_length=9,
                    ),
                ),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_note", models.TextField(blank=True)),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True,
                        help_text="Provider reference for future licensed beneficiary verification API",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_accounts",
                        to="employees.bank",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_accounts",
                        to="employees.bankbranch",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="employees.employee",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Bank Account",
                "verbose_name_plural": "Employee Bank Accounts",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
    ]
