# Generated by Django 5.2.14 on 2026-09-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0029_bank_bankbranch_employeebankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('cash', 'Cash'), ('mfs', 'Mobile Financial Service'), ('mobile', 'Mobile Banking')], default='bank', max_length=30),
        ),
    ]
