# Generated by Django 5.2.14 on 2026-07-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending_manager', 'Pending Manager Approval'), ('pending_finance', 'Pending Finance Approval'), ('pending_accounts', 'Pending Accounts Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_manager', max_length=20),
        ),
    ]
