# Generated by Django 5.2.14 on 2026-07-25 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_managerdelegation'),
        ('expense', '0003_expensecategory_alter_expense_status_and_more'),
        ('projects', '0022_dailyprogresslog_client_event_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/history/')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseReturnEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_from_status', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('fields_to_correct', models.JSONField(blank=True, default=list)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/returns/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_manager', 'Pending Manager Approval'), ('pending_finance', 'Pending Finance Approval'), ('pending_accounts', 'Pending Accounts Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned for Correction'), ('returned_by_manager', 'Returned by Manager'), ('returned_by_finance', 'Returned by Finance')], default='draft', max_length=30),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status'], name='expense_exp_status_4d58ed_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['employee'], name='expense_exp_employe_8b012e_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='expense_exp_categor_f573f2_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['requested_at'], name='expense_exp_request_370b9c_idx'),
        ),
        migrations.AddField(
            model_name='expensehistory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.expensecategory'),
        ),
        migrations.AddField(
            model_name='expensehistory',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='expense.expense'),
        ),
        migrations.AddField(
            model_name='expensehistory',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensereturnevent',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_events', to='expense.expense'),
        ),
        migrations.AddField(
            model_name='expensereturnevent',
            name='returned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
