# Generated by Django 5.2.14 on 2026-07-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("check_in", "Check In"),
                    ("check_out", "Check Out"),
                    ("field_visit", "Field Visit"),
                    ("late", "Late Alert"),
                    ("missing", "Missing Employee"),
                    ("document_expiry", "Document Expiry"),
                ],
                max_length=20,
            ),
        ),
    ]
