# Generated by Django 5.2.14 on 2026-07-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("check_in", "Check In"),
                    ("check_out", "Check Out"),
                    ("field_visit", "Field Visit"),
                    ("late", "Late Alert"),
                    ("missing", "Missing Employee"),
                    ("document_expiry", "Document Expiry"),
                    ("task_assigned", "Task Assigned"),
                    ("task_completed", "Task Completed"),
                    ("task_delayed", "Task Delayed"),
                    ("role_changed", "Role/Group Changed"),
                    ("permission_changed", "Permission Changed"),
                    ("lifecycle_request", "Lifecycle Transition Request"),
                    ("lifecycle_reviewed", "Lifecycle Request Reviewed"),
                ],
                max_length=50,
            ),
        ),
    ]
